#install.packages("cancensus")
library(cancensus)
options(cancensus.api_key='CensusMapper_17d2ce97fde1a6b31319965bb10d0fb0')
options(cancensus.cancensus.cache_path ="~")
toronto_ct <- get_census(dataset='CA16', regions=list(CMA="35535"), vectors=c(), labels="detailed", geo_format="sf", level='CT')
toronto_da<- get_census(dataset='CA16', regions=list(CMA="35535"), vectors=c(), labels="detailed", geo_format="sf", level='DA')
library(ggplot2)
ggplot(toronto_ct,aes(geometry=geometry,fill=Population))+geom_sf()
ggsave("population.jpg")
